# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-07 08:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('val', models.DecimalField(decimal_places=1, max_digits=2)),
                ('classified_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classified_player_id', to='events.Player')),
                ('classifying_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifying_player_id', to='events.Player')),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='players',
            field=models.ManyToManyField(null=True, to='events.Player'),
        ),
        migrations.AddField(
            model_name='classification',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event'),
        ),
        migrations.AlterUniqueTogether(
            name='classification',
            unique_together=set([('classified_player', 'classifying_player', 'event')]),
        ),
    ]
