# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-07 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20160507_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='players',
            field=models.ManyToManyField(blank=True, to='events.Player'),
        ),
    ]
