# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 19:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('val', models.DecimalField(decimal_places=1, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='players',
            field=models.ManyToManyField(blank=True, to='kitella.Player'),
        ),
        migrations.AddField(
            model_name='classification',
            name='classified_player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classified_player_id', to='kitella.Player'),
        ),
        migrations.AddField(
            model_name='classification',
            name='classifying_player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifying_player_id', to='kitella.Player'),
        ),
        migrations.AddField(
            model_name='classification',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitella.Event'),
        ),
        migrations.AlterUniqueTogether(
            name='classification',
            unique_together=set([('classified_player', 'classifying_player', 'event')]),
        ),
    ]
